inherit_from: .rubocop_todo.yml

Metrics/BlockNesting:
  Max: 2

Layout/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
